"""Audit an RL run before trusting, resuming, scaling, or packaging it.

The first long Lucario run looked healthy in aggregate (252,448 games and no
invalid actions) while 85.7% of its games were generated by stale policies.
This command checks policy provenance as a first-class invariant, along with
resume continuity, encoder/pool identity, numerical update health, and deck/card
coverage.  It exits non-zero with ``--strict`` when a correctness invariant
fails; sample-efficiency warnings remain warnings unless an explicit minimum is
requested.
"""
from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import json
import os
from pathlib import Path
import statistics
from typing import Any

import torch


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def pool_coverage(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as source:
        payload = json.load(source)
    learner = payload.get("learner_decks") or []
    field = payload.get("field_decks") or []
    learner_cards = {int(card) for deck in learner for card in deck.get("cards", [])}
    field_cards = {int(card) for deck in field for card in deck.get("cards", [])}
    return {
        "learner_decks": len(learner),
        "field_decks": len(field),
        "learner_unique_cards": len(learner_cards),
        "field_unique_cards": len(field_cards),
        "union_unique_cards": len(learner_cards | field_cards),
    }


def mean(rows: list[float]) -> float:
    return statistics.fmean(rows) if rows else 0.0


def audit(run_dir: Path, min_unique_cards: int = 0) -> dict[str, Any]:
    jsonl_path = run_dir / "metrics.jsonl"
    metrics_path = run_dir / "metrics.json"
    config_path = run_dir / "run_config.json"
    if jsonl_path.is_file():
        with jsonl_path.open(encoding="utf-8") as source:
            periods = [json.loads(line) for line in source if line.strip()]
        if not config_path.is_file():
            raise FileNotFoundError(f"missing {config_path} for JSONL metrics")
        with config_path.open(encoding="utf-8") as source:
            config = (json.load(source).get("config") or {})
    elif metrics_path.is_file():
        with metrics_path.open(encoding="utf-8") as source:
            payload = json.load(source)
        config = payload.get("config") or {}
        periods = payload.get("periods") or []
    else:
        raise FileNotFoundError(f"missing {jsonl_path} and {metrics_path}")
    failures: list[str] = []
    warnings: list[str] = []

    period_ids = [int(row.get("period", -1)) for row in periods]
    duplicates = sorted(pid for pid, count in Counter(period_ids).items() if count > 1)
    expected = list(range(period_ids[0], period_ids[-1] + 1)) if period_ids else []
    if not periods:
        failures.append("no completed periods")
    if duplicates:
        failures.append(f"duplicate period IDs: {duplicates[:12]}")
    if period_ids != expected:
        failures.append("period IDs are not strictly contiguous and increasing")

    total_games = 0
    total_decisions = 0
    total_errors = 0
    total_invalid = 0
    lag = Counter()
    missing_provenance = 0
    opponent_decks = Counter()
    learner_decks = Counter()
    approx_kls: list[float] = []
    clip_fractions: list[float] = []
    ref_kls: list[float] = []
    optimizer_steps = 0
    for period in periods:
        pid = int(period.get("period", -1))
        games = period.get("games") or []
        game_count = int(period.get("games_count", len(games)))
        total_games += game_count
        total_decisions += int(period.get("decisions", 0))
        total_errors += int(period.get("errors", 0))
        total_invalid += int(period.get("invalid_actions", 0))
        learner_decks.update(str(row.get("learner_deck", "?")) for row in games)
        opponent_decks.update(str(row.get("opponent_deck", "?")) for row in games)
        if not games:
            for name, matchup in (period.get("matchups") or {}).items():
                opponent_decks[str(name)] += int(matchup.get("games", 0))
        explicit = period.get("policy_lag_counts")
        if isinstance(explicit, dict):
            for key, count in explicit.items():
                lag[int(key)] += int(count)
        else:
            for game in games:
                source = game.get("policy_period", game.get("period"))
                if source is None:
                    missing_provenance += 1
                else:
                    lag[pid - int(source)] += 1
        update = period.get("update") or {}
        if "approx_kl" in update:
            approx_kls.append(float(update["approx_kl"]))
        if "clip_fraction" in update:
            clip_fractions.append(float(update["clip_fraction"]))
        if "ref_kl" in update:
            ref_kls.append(float(update["ref_kl"]))
        optimizer_steps += int(update.get("optimizer_steps", 0))

    stale = sum(count for amount, count in lag.items() if amount != 0)
    sourced = sum(lag.values())
    stale_fraction = stale / sourced if sourced else 0.0
    if sourced != total_games:
        failures.append(
            f"policy provenance covers {sourced}/{total_games} games"
        )
    if config.get("async_rollout"):
        failures.append("run used the unsafe cross-update async collector")
    if stale:
        failures.append(
            f"{stale}/{sourced} sourced games ({stale_fraction:.1%}) have non-zero policy lag"
        )
    if missing_provenance:
        warnings.append(f"{missing_provenance} games have no policy provenance")
    if total_errors:
        failures.append(f"engine errors: {total_errors}")
    if total_invalid:
        failures.append(f"invalid actions: {total_invalid}")
    if any(int(row.get("decisions", 0)) <= 0 for row in periods):
        failures.append("at least one period has no training decisions")

    target_kl = float(config.get("target_kl", 0.0) or 0.0)
    if target_kl and approx_kls and max(approx_kls) > target_kl * 2.0:
        warnings.append(
            f"maximum reported KL {max(approx_kls):.4f} exceeds 2x target {target_kl:.4f}"
        )
    if clip_fractions and mean(clip_fractions) > 0.25:
        warnings.append(f"mean clip fraction is high ({mean(clip_fractions):.3f})")

    pool_report = None
    pool_name = config.get("pool")
    if pool_name:
        pool_path = Path(pool_name)
        if not pool_path.is_file():
            failures.append(f"configured pool is missing: {pool_path}")
        else:
            pool_report = pool_coverage(pool_path)
            expected_hash = config.get("pool_sha256")
            if expected_hash and sha256(pool_path) != expected_hash:
                failures.append("deck-pool bytes changed since the run started")
            if min_unique_cards and pool_report["union_unique_cards"] < min_unique_cards:
                failures.append(
                    f"pool covers {pool_report['union_unique_cards']} unique cards, "
                    f"below requested minimum {min_unique_cards}"
                )

    state_path = run_dir / "training_state.pt"
    state_period = None
    if state_path.is_file():
        state = torch.load(state_path, map_location="cpu", weights_only=False)
        state_period = int(state.get("period", -1))
        if period_ids and state_period != period_ids[-1]:
            failures.append(
                f"training_state period {state_period} != metrics period {period_ids[-1]}"
            )
    else:
        warnings.append("training_state.pt is missing; run cannot resume exactly")

    if config.get("champion_format_export") and int(config.get("max_opt", -1)) != 24:
        failures.append("checkpoint claims champion export under a non-24 MAX_OPT ABI")
    if total_games < 3_000_000:
        warnings.append(
            f"{total_games:,} games is only {total_games / 3_000_000:.1%} of the "
            "3M-game lower bound reported in the public RL discussion"
        )

    return {
        "run_dir": str(run_dir.resolve()),
        "periods": len(periods),
        "first_period": period_ids[0] if period_ids else None,
        "last_period": period_ids[-1] if period_ids else None,
        "state_period": state_period,
        "games": total_games,
        "decisions": total_decisions,
        "optimizer_steps": optimizer_steps,
        "policy_lag_counts": dict(sorted(lag.items())),
        "stale_fraction": stale_fraction,
        "errors": total_errors,
        "invalid_actions": total_invalid,
        "mean_approx_kl": mean(approx_kls),
        "max_approx_kl": max(approx_kls, default=0.0),
        "mean_clip_fraction": mean(clip_fractions),
        "mean_reference_kl": mean(ref_kls),
        "learner_decks": dict(learner_decks.most_common()),
        "opponent_decks": dict(opponent_decks.most_common()),
        "pool": pool_report,
        "failures": failures,
        "warnings": warnings,
        "ready_to_scale": not failures,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("run_dir", type=Path)
    parser.add_argument("--min-unique-cards", type=int, default=0)
    parser.add_argument("--json-out", type=Path)
    parser.add_argument("--strict", action="store_true")
    args = parser.parse_args()
    report = audit(args.run_dir, args.min_unique_cards)
    print(json.dumps(report, indent=2))
    if args.json_out:
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    if args.strict and report["failures"]:
        raise SystemExit(2)


if __name__ == "__main__":
    main()
