"""Resource-bounded, version-audited PPO with a historical opponent league.

Every update is made from a complete batch generated by one frozen behaviour
policy.  Rollouts never overlap a learner update: the previous async path
quietly trained on a one-to-three-version stale backlog, which is off-policy
learning rather than PPO.  A run may start from behaviour-cloned weights, in
which case it is intentionally BC-initialised and not replay-free.
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass
import glob
import hashlib
import json
import math
import os
import random
import re
import shutil
import time

import numpy as np
import torch

from foundation import nn_features_rich as NF

from .bc_init import export_champion_npz, load_bc_checkpoint
from .network import ActorCritic, NetworkConfig, config_dict, export_npz
from .policy import Decision, batch_logprob_entropy
from .rollout import GameTask, RolloutPool


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


@dataclass
class LeagueEntry:
    """A historical opponent, referenced by file so workers can load it.

    Holding paths rather than modules keeps the parent's memory flat as the
    league grows and lets a resumed run rebuild the league from disk.
    """
    period: int
    path: str
    candidate_win_rate: float = 0.5


def load_pool(path: str) -> tuple[list[dict], list[dict], dict]:
    with open(path, encoding="utf-8") as source:
        payload = json.load(source)
    learner = payload.get("learner_decks") or []
    field = payload.get("field_decks") or []
    for group_name, group in (("learner_decks", learner), ("field_decks", field)):
        if not group:
            raise ValueError(f"{group_name} is empty")
        for item in group:
            cards = item.get("cards")
            if not isinstance(cards, list) or len(cards) != 60 or not all(
                isinstance(card, int) for card in cards
            ):
                raise ValueError(f"invalid deck in {group_name}: {item.get('name')}")
    return learner, field, payload


def weighted_deck(
    rng: random.Random, decks: list[dict], uniform_probability: float = 0.0
) -> dict:
    # A uniform curriculum component prevents the largest archetype from
    # starving rare counter-strategies. The remaining mass still follows the
    # square-root ladder frequency, so the field is recognisably current.
    if uniform_probability > 0.0 and rng.random() < uniform_probability:
        return rng.choice(decks)
    weights = [math.sqrt(max(1.0, float(deck.get("appearances", 1)))) for deck in decks]
    return rng.choices(decks, weights=weights, k=1)[0]


def choose_league_opponent(rng: random.Random, league: list[LeagueEntry]) -> LeagueEntry:
    # Prioritized fictitious play: spend more games on snapshots the learner
    # has not yet beaten, but retain a floor so cyclic older policies survive.
    weights = [max(0.08, 1.0 - entry.candidate_win_rate) for entry in league]
    return rng.choices(league, weights=weights, k=1)[0]


def resource_guard(args: argparse.Namespace) -> None:
    if not (1 <= args.periods <= 50_000):
        raise ValueError("--periods must be in [1, 50000]")
    if not (4 <= args.games_per_period <= 512):
        raise ValueError("--games-per-period must be in [4, 512]")
    if not (500 <= args.max_decisions <= 200_000):
        raise ValueError("--max-decisions must be in [500, 200000]")
    if not (1 <= args.threads <= 16):
        raise ValueError("--threads must be in [1, 16]")
    cores = os.cpu_count() or 1
    if not (1 <= args.workers <= max(1, cores)):
        raise ValueError(f"--workers must be in [1, {cores}]")
    # Oversubscription measurably slows rollouts: the pool contends with itself
    # and with the parent, so refuse a configuration that cannot fit.
    if args.workers * args.threads_per_worker > cores:
        raise ValueError(
            f"--workers x --threads-per-worker ({args.workers * args.threads_per_worker}) "
            f"exceeds {cores} cores"
        )
    available = None
    try:
        with open("/proc/meminfo", encoding="utf-8") as source:
            fields = {
                line.split(":", 1)[0]: int(line.split()[1]) * 1024
                for line in source if ":" in line
            }
        available = fields.get("MemAvailable")
    except OSError:
        pass
    # Stored observations are ~18 KiB after the 64-option correction. Keep a
    # 4x margin for tensors, optimizer state, arena, and historical policies.
    required = args.max_decisions * 18 * 1024 * 4 + 3 * 1024**3
    if available is not None and required > available * 0.70:
        raise RuntimeError(
            f"configuration needs a conservative {required / 2**30:.1f} GiB; "
            f"only {available / 2**30:.1f} GiB is available"
        )
    os.makedirs(args.out_dir, exist_ok=True)
    if shutil.disk_usage(args.out_dir).free < 10 * 1024**3:
        raise RuntimeError("less than 10 GiB free on the checkpoint filesystem")


def file_sha256(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def gpu_telemetry(device: torch.device) -> dict[str, float] | None:
    """Peak VRAM and thermals for the period, so a long run stays auditable.

    The update is a short burst against a long CPU rollout, so the card should
    show a low duty cycle; a climbing peak here means the batch is too large.
    """
    if device.type != "cuda":
        return None
    free, total = torch.cuda.mem_get_info()
    telemetry = {
        "peak_allocated_mib": torch.cuda.max_memory_allocated() / 2**20,
        "peak_reserved_mib": torch.cuda.max_memory_reserved() / 2**20,
        "device_used_mib": (total - free) / 2**20,
        "device_total_mib": total / 2**20,
    }
    for name, key in (("temperature", "temperature_c"), ("power", "power_w")):
        try:
            if name == "temperature":
                telemetry[key] = float(torch.cuda.temperature())
            else:
                telemetry[key] = float(torch.cuda.power_draw()) / 1000.0
        except Exception:
            pass  # not every driver/build exposes these
    torch.cuda.reset_peak_memory_stats()
    return telemetry


def tensor_batch(batch: list[Decision], device: torch.device) -> dict[str, torch.Tensor]:
    return {
        "kind": torch.as_tensor(
            np.stack([x.kind for x in batch]).astype(np.int64), device=device
        ),
        "card": torch.as_tensor(
            np.stack([x.card for x in batch]).astype(np.int64), device=device
        ),
        "scal": torch.as_tensor(np.stack([x.scal for x in batch]), device=device),
        "mask": torch.as_tensor(np.stack([x.mask for x in batch]), device=device),
        "ctx": torch.as_tensor([x.ctx for x in batch], device=device),
        "stype": torch.as_tensor([x.stype for x in batch], device=device),
        "selected_slots": torch.as_tensor(
            np.stack([x.selected_slots for x in batch]).astype(np.int64), device=device
        ),
        "selected_count": torch.as_tensor(
            [x.selected_count for x in batch], device=device
        ),
        "low_count": torch.as_tensor([x.low_count for x in batch], device=device),
        "high_count": torch.as_tensor([x.high_count for x in batch], device=device),
        "old_logp": torch.as_tensor([x.old_logp for x in batch], device=device),
        "returns": torch.as_tensor([x.outcome for x in batch], device=device),
        "advantage": torch.as_tensor([x.advantage for x in batch], device=device),
    }


def optimizer_to(optimizer: torch.optim.Optimizer, device: torch.device | str) -> None:
    """Move Adam moments with the model across CPU rollout / GPU update phases."""
    for state in optimizer.state.values():
        for key, value in state.items():
            if torch.is_tensor(value):
                state[key] = value.to(device)


def ppo_update(
    model: ActorCritic,
    decisions: list[Decision],
    optimizer: torch.optim.Optimizer,
    device: torch.device,
    rng: random.Random,
    args: argparse.Namespace,
    reference: ActorCritic | None = None,
) -> dict[str, float]:
    """One PPO step, optionally anchored to a frozen reference policy.

    `--target-kl` bounds movement away from the **behaviour** policy, which is
    last period's weights. It says nothing about total drift: across a hundred
    periods the policy can walk arbitrarily far from where it started while
    every individual step stays inside the trust region.

    That matters here more than in ordinary RL, because this network does not
    ship as a policy. It ships as the **prior** of the frozen search, and a
    prior is not judged by how well it plays alone. The one time this project
    put an RL policy behind the shell (`submission_ppo_bcsearch`, v3 PPO from
    random init) it finished last at 8.3%, below the same agent with *no*
    network at all, because an overconfident prior decides which subtrees PUCT
    ever expands.

    So when `--ref-kl-coef` is set, the loss carries a penalty on divergence
    from the BC prior, using Schulman's k3 estimator, which is non-negative and
    lower variance than the plain log-ratio. `ref_kl` is reported per period so
    the drift away from the weights that actually scored 972 is visible rather
    than inferred.
    """
    raw_advantage = np.asarray(
        [decision.outcome - decision.old_value for decision in decisions],
        dtype=np.float32,
    )
    mean, std = float(raw_advantage.mean()), float(raw_advantage.std())
    normalized = (raw_advantage - mean) / (std + 1e-6)
    for decision, advantage in zip(decisions, normalized):
        decision.advantage = float(advantage)

    model.to(device).train()
    # Resumable state is intentionally saved on CPU. Without moving Adam's
    # moments back here, the first update after a CUDA resume mixes CPU momentum
    # with CUDA gradients and crashes only after the new rollout has completed.
    optimizer_to(optimizer, device)
    order = list(range(len(decisions)))
    totals = {"loss": 0.0, "policy": 0.0, "value": 0.0, "entropy": 0.0,
              "approx_kl": 0.0, "clip_fraction": 0.0, "ref_kl": 0.0}
    anchored = reference is not None and args.ref_kl_coef > 0.0
    if anchored:
        reference.to(device).eval()
    steps = 0
    stopped_early = False
    for _epoch in range(args.epochs):
        rng.shuffle(order)
        epoch_kl = []
        for start in range(0, len(order), args.batch):
            batch = [decisions[i] for i in order[start : start + args.batch]]
            data = tensor_batch(batch, device)
            option, count, value = model(
                data["kind"], data["card"], data["scal"], data["mask"],
                data["ctx"], data["stype"],
            )
            # Rollouts sample from logits / temperature. Recomputing PPO ratios
            # from the untempered logits is only correct at temperature=1 and
            # silently corrupts every exploration run at any other setting.
            policy_temperature = max(float(args.temperature), 1e-3)
            option = option / policy_temperature
            count = count / policy_temperature
            logp, entropy = batch_logprob_entropy(
                option, count, data["kind"], data["mask"],
                data["selected_slots"], data["selected_count"],
                data["low_count"], data["high_count"],
            )
            log_ratio = (logp - data["old_logp"]).clamp(-20.0, 20.0)
            ratio = log_ratio.exp()
            unclipped = ratio * data["advantage"]
            clipped = ratio.clamp(1.0 - args.clip, 1.0 + args.clip) * data["advantage"]
            policy_loss = -torch.minimum(unclipped, clipped).mean()
            value_loss = 0.5 * (value - data["returns"]).square().mean()
            entropy_mean = entropy.mean()
            loss = policy_loss + args.value_coef * value_loss - args.entropy_coef * entropy_mean

            ref_kl_value = 0.0
            if anchored:
                with torch.no_grad():
                    ref_option, ref_count, _ = reference(
                        data["kind"], data["card"], data["scal"], data["mask"],
                        data["ctx"], data["stype"],
                    )
                    ref_option = ref_option / policy_temperature
                    ref_count = ref_count / policy_temperature
                    ref_logp, _ = batch_logprob_entropy(
                        ref_option, ref_count, data["kind"], data["mask"],
                        data["selected_slots"], data["selected_count"],
                        data["low_count"], data["high_count"],
                    )
                # Schulman k3: exp(d) - d - 1 with d = ref_logp - logp. It is
                # always >= 0 and approximates KL(policy || reference); actions
                # came from the frozen behaviour policy, not exactly `policy`.
                delta = (ref_logp - logp).clamp(-20.0, 20.0)
                ref_kl = (delta.exp() - delta - 1.0).mean()
                loss = loss + args.ref_kl_coef * ref_kl
                ref_kl_value = float(ref_kl.detach())

            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
            optimizer.step()

            # The signed mean(old_logp - new_logp) used here previously is a
            # noisy KL estimator whose positive and negative terms cancel. It
            # can report ~0 while many actions are already clipped. This
            # non-negative k3 form is the standard PPO early-stop diagnostic.
            approx_kl = float(
                ((ratio - 1.0) - log_ratio).mean().detach()
            )
            clip_fraction = float(((ratio - 1.0).abs() > args.clip).float().mean().detach())
            values = {
                "loss": float(loss.detach()), "policy": float(policy_loss.detach()),
                "value": float(value_loss.detach()), "entropy": float(entropy_mean.detach()),
                "approx_kl": approx_kl, "clip_fraction": clip_fraction,
                "ref_kl": ref_kl_value,
            }
            for key, item in values.items():
                totals[key] += item
            epoch_kl.append(approx_kl)
            steps += 1
            # Checking only at epoch end is too coarse: at a large decision
            # budget an epoch is dozens of minibatches, so the policy can move
            # far past the trust region before the guard ever looks. Stop on
            # the first minibatch that exceeds it.
            if approx_kl > args.target_kl:
                stopped_early = True
                break
        if stopped_early:
            break
        if epoch_kl and sum(epoch_kl) / len(epoch_kl) > args.target_kl:
            stopped_early = True
            break
    model.to("cpu").eval()
    optimizer_to(optimizer, "cpu")
    if anchored:
        reference.to("cpu").eval()
    return {
        **{key: value / max(steps, 1) for key, value in totals.items()},
        "optimizer_steps": steps,
        "advantage_mean_raw": mean,
        "advantage_std_raw": std,
        "early_stop": float(stopped_early),
    }


def evaluation_tasks(
    candidate_path: str,
    league: list[LeagueEntry],
    learner_decks: list[dict],
    field_decks: list[dict],
    games: int,
) -> list[GameTask]:
    """Every league member's evaluation games, flattened for one parallel pass."""
    tasks = []
    for entry in league:
        for game_index in range(games):
            candidate_seat = game_index % 2
            own = learner_decks[game_index % len(learner_decks)]["cards"]
            other = field_decks[game_index % len(field_decks)]["cards"]
            if candidate_seat == 0:
                models, decks = (candidate_path, entry.path), (own, other)
            else:
                models, decks = (entry.path, candidate_path), (other, own)
            tasks.append(GameTask(
                left_model=models[0], right_model=models[1],
                left_deck=decks[0], right_deck=decks[1],
                record_seats=(), sample=False,
                seed=hash((entry.period, game_index)) & 0xFFFFFFFF,
                meta={"history_period": entry.period, "candidate_seat": candidate_seat},
            ))
    return tasks


def fold_evaluations(outcomes, league: list[LeagueEntry]) -> list[dict]:
    """Reduce flat evaluation outcomes back into one row per league member."""
    totals = {
        entry.period: {"wins": 0, "losses": 0, "draws": 0, "errors": 0, "invalid_actions": 0}
        for entry in league
    }
    for outcome in outcomes:
        record = totals[outcome.meta["history_period"]]
        seat = outcome.meta["candidate_seat"]
        record["invalid_actions"] += outcome.invalid_actions
        if outcome.error:
            record["errors"] += 1
        elif outcome.winner == seat:
            record["wins"] += 1
        elif outcome.winner == 1 - seat:
            record["losses"] += 1
        else:
            record["draws"] += 1
    rows = []
    for entry in league:
        record = totals[entry.period]
        decided = record["wins"] + record["losses"]
        record["win_rate"] = record["wins"] / decided if decided else 0.0
        entry.candidate_win_rate = float(record["win_rate"])
        rows.append({"history_period": entry.period, **record})
    return rows


def rebuild_league(out_dir: str, max_history: int) -> list[LeagueEntry]:
    """Reconstruct the league from archived snapshots when resuming."""
    entries = []
    for path in sorted(glob.glob(os.path.join(out_dir, "league_*.npz"))):
        match = re.search(r"league_(\d+)\.npz$", path)
        if match:
            entries.append(LeagueEntry(int(match.group(1)), path))
    while len(entries) > max_history:
        del entries[1]  # keep the initial anchor, drop the oldest after it
    return entries


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pool", default=os.path.join(ROOT, "data", "fresh", "deck_pool.json"))
    parser.add_argument("--out-dir", default=os.path.join(ROOT, "rl_osfp", "run"))
    parser.add_argument("--periods", type=int, default=12)
    parser.add_argument("--games-per-period", type=int, default=24)
    parser.add_argument("--eval-games", type=int, default=4)
    parser.add_argument("--max-decisions", type=int, default=14_000)
    parser.add_argument("--epochs", type=int, default=2)
    parser.add_argument("--batch", type=int, default=384)
    parser.add_argument("--lr", type=float, default=7e-5)
    parser.add_argument(
        "--anneal-lr", action=argparse.BooleanOptionalAction, default=True,
        help="linearly decay the PPO learning rate to 10%% of --lr across "
             "--periods; enabled by default for multi-million-game runs",
    )
    parser.add_argument("--clip", type=float, default=0.2)
    parser.add_argument("--value-coef", type=float, default=1.0)
    parser.add_argument("--entropy-coef", type=float, default=0.01)
    parser.add_argument("--grad-clip", type=float, default=0.8)
    parser.add_argument("--target-kl", type=float, default=0.04)
    parser.add_argument("--self-play-prob", type=float, default=0.60)
    parser.add_argument(
        "--uniform-field-prob", type=float, default=0.25,
        help="fraction of field-deck draws made uniformly instead of by "
             "sqrt(ladder appearances), preserving rare counter-strategies",
    )
    parser.add_argument("--archive-threshold", type=float, default=0.55)
    parser.add_argument("--archive-max-wait", type=int, default=3)
    parser.add_argument("--max-history", type=int, default=12)
    parser.add_argument("--temperature", type=float, default=1.0)
    parser.add_argument("--threads", type=int, default=8,
                        help="torch threads in the parent, used for the PPO update")
    parser.add_argument("--workers", type=int, default=max(1, (os.cpu_count() or 2) - 2),
                        help="rollout worker processes; the engine is process-global "
                             "so parallelism cannot be threads")
    parser.add_argument("--threads-per-worker", type=int, default=1)
    parser.add_argument("--max-recorded-per-seat", type=int, default=1200,
                        help="per-game, per-seat cap on recorded decisions")
    parser.add_argument(
        "--checkpoint-every", type=int, default=10,
        help="write numbered model/champion checkpoints every N periods; "
             "model_latest and resumable state are still written every period",
    )
    parser.add_argument(
        "--record-game-rows", action=argparse.BooleanOptionalAction, default=False,
        help="embed every game's metadata in append-only metrics JSONL; disabled "
             "by default because millions of games need aggregate diagnostics",
    )
    parser.add_argument("--ref-kl-coef", type=float, default=0.0,
                        help="penalty on KL from the --init prior. `--target-kl` "
                             "only bounds movement per period, so without this "
                             "the policy drifts arbitrarily far from the BC "
                             "weights over a long run. The network ships as the "
                             "frozen search's prior, and an overconfident prior "
                             "measured 8.3% behind that shell, so staying near "
                             "the prior is the point. Try 0.05 to 0.2.")
    parser.add_argument("--init", default=None,
                        help="BC checkpoint (.npz) to start from instead of random "
                             "weights. Accepts the champion's own model.npz; the "
                             "trunks are identical and sequence length does not "
                             "have to match. See rl_osfp/bc_init.py.")
    parser.add_argument("--resume", action="store_true",
                        help="continue from training_state.pt in --out-dir")
    parser.add_argument("--max-wall-minutes", type=float, default=480.0)
    parser.add_argument("--async-rollout", action="store_true",
                        help="deprecated compatibility flag. Rollouts are still "
                             "synchronised at every PPO update because the old "
                             "cross-update producer made 85.7%% of the Lucario "
                             "run off-policy")
    parser.add_argument("--eval-every", type=int, default=1,
                        help="run the league evaluation batch every Nth period. "
                             "It costs --eval-games per league member (up to "
                             "48 games) and produces no training data")
    parser.add_argument("--device", choices=("auto", "cpu", "cuda"), default="auto")
    parser.add_argument("--seed", type=int, default=20260803)
    args = parser.parse_args()
    resource_guard(args)
    if not (0.0 < args.self_play_prob <= 1.0):
        parser.error("--self-play-prob must be in (0, 1]")
    if not (0.0 <= args.uniform_field_prob <= 1.0):
        parser.error("--uniform-field-prob must be in [0, 1]")
    if not (0.05 <= args.temperature <= 5.0):
        parser.error("--temperature must be in [0.05, 5]")
    if args.checkpoint_every < 1:
        parser.error("--checkpoint-every must be positive")
    if args.async_rollout:
        print(
            "WARNING: --async-rollout is deprecated and now runs in safe "
            "synchronised mode; no game may cross a PPO update",
            flush=True,
        )

    torch.set_num_threads(args.threads)
    if args.device == "cuda" and not torch.cuda.is_available():
        parser.error("CUDA requested but unavailable")
    device_name = (
        "cuda" if torch.cuda.is_available() else "cpu"
    ) if args.device == "auto" else args.device
    device = torch.device(device_name)
    if device.type == "cuda":
        torch.cuda.set_per_process_memory_fraction(0.72)

    rng = random.Random(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(args.seed)
    learner_decks, field_decks, pool_payload = load_pool(args.pool)
    reference: ActorCritic | None = None
    if args.init:
        # Start from the behaviour-cloned prior rather than from noise.  Every
        # RL run in this repo before 2026-08-06 started random, not because
        # BC init was tried and rejected but because there was no way to load
        # it.  Random init is also the only measured difference between the
        # arm that reached 480 and the arm that reached 972.
        model, net_cfg, init_report = load_bc_checkpoint(args.init)
        model = model.to("cpu").eval()
        print(f"initialised from {args.init}: {init_report}", flush=True)
        if args.ref_kl_coef > 0.0:
            # A second, frozen copy of the same weights. This is the thing the
            # policy is not allowed to wander away from, because it is the prior
            # the shipped search actually depends on.
            reference, _, _ = load_bc_checkpoint(args.init)
            reference = reference.to("cpu").eval()
            for parameter in reference.parameters():
                parameter.requires_grad_(False)
    else:
        net_cfg = NetworkConfig()
        init_report = None
        model = ActorCritic(net_cfg).to("cpu").eval()  # random initialization
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=1e-5)
    league: list[LeagueEntry] = []
    metrics: list[dict] = []
    since_archive = 0
    first_period = 1
    work_dir = os.path.join(args.out_dir, "_work")
    os.makedirs(work_dir, exist_ok=True)

    existing_run_files = (
        "training_state.pt", "metrics.json", "metrics.jsonl", "run_config.json"
    )
    if not args.resume and any(
        os.path.isfile(os.path.join(args.out_dir, name)) for name in existing_run_files
    ):
        raise SystemExit(
            f"{args.out_dir} already contains run state/metrics; pass --resume "
            "or choose a new --out-dir so checkpoints are not overwritten"
        )

    if args.resume:
        state_path = os.path.join(args.out_dir, "training_state.pt")
        if not os.path.isfile(state_path):
            raise SystemExit(f"--resume needs {state_path}")
        state = torch.load(state_path, map_location="cpu", weights_only=False)
        saved_config = state.get("config") or {}
        saved_pool = saved_config.get("pool")
        if saved_pool and os.path.abspath(args.pool) != saved_pool:
            raise SystemExit(
                f"refusing resume with a different pool: {saved_pool} -> "
                f"{os.path.abspath(args.pool)}"
            )
        saved_pool_sha = saved_config.get("pool_sha256")
        current_pool_sha = file_sha256(args.pool)
        if saved_pool_sha and current_pool_sha != saved_pool_sha:
            raise SystemExit(
                "refusing resume because the deck-pool contents changed: "
                f"{saved_pool_sha[:12]} -> {current_pool_sha[:12]}"
            )
        saved_max_opt = saved_config.get("max_opt")
        if saved_max_opt is not None and int(saved_max_opt) != NF.MAX_OPT:
            raise SystemExit(
                f"refusing resume across encoder ABI: MAX_OPT "
                f"{saved_max_opt} -> {NF.MAX_OPT}"
            )
        if saved_config.get("async_rollout"):
            raise SystemExit(
                "this checkpoint was produced by the unsafe cross-update "
                "async collector; start a clean run instead of resuming it"
            )
        # These define the data distribution or PPO objective. Changing one on
        # resume creates a new experiment, so use another output directory.
        resume_critical = (
            "games_per_period", "max_decisions", "epochs", "batch", "lr",
            "anneal_lr", "clip", "value_coef", "entropy_coef", "grad_clip",
            "target_kl", "self_play_prob", "archive_threshold",
            "uniform_field_prob",
            "archive_max_wait", "max_history", "temperature", "ref_kl_coef",
            "seed", "periods",
        )
        for key in resume_critical:
            if key in saved_config and saved_config[key] != getattr(args, key):
                raise SystemExit(
                    f"refusing resume with changed --{key.replace('_', '-')}: "
                    f"{saved_config[key]!r} -> {getattr(args, key)!r}"
                )
        saved_init = saved_config.get("init_checkpoint")
        current_init = os.path.abspath(args.init) if args.init else None
        if saved_init != current_init:
            raise SystemExit(
                "refusing resume with a different BC anchor: "
                f"{saved_init!r} -> {current_init!r}"
            )
        model.load_state_dict(state["model"])
        optimizer.load_state_dict(state["optimizer"])
        first_period = int(state["period"]) + 1
        since_archive = int(state.get("since_archive", 0))
        league = rebuild_league(args.out_dir, args.max_history)
        jsonl_path = os.path.join(args.out_dir, "metrics.jsonl")
        legacy_metrics_path = os.path.join(args.out_dir, "metrics.json")
        if os.path.isfile(jsonl_path):
            with open(jsonl_path, encoding="utf-8") as source:
                metrics = [json.loads(line) for line in source if line.strip()]
        elif os.path.isfile(legacy_metrics_path):
            with open(legacy_metrics_path, encoding="utf-8") as source:
                metrics = json.load(source).get("periods") or []
        if not metrics or int(metrics[-1].get("period", -1)) != int(state["period"]):
            raise SystemExit(
                "refusing resume because metrics and training_state are not at "
                f"the same completed period ({metrics[-1].get('period') if metrics else None} "
                f"vs {state['period']})"
            )
        print(
            f"resumed at period {first_period} with league "
            f"{[entry.period for entry in league]}",
            flush=True,
        )
        if "python_rng" in state:
            rng.setstate(state["python_rng"])
        if "numpy_rng" in state:
            np.random.set_state(state["numpy_rng"])
        if "torch_rng" in state:
            torch.set_rng_state(state["torch_rng"])
        if device.type == "cuda" and state.get("cuda_rng") is not None:
            torch.cuda.set_rng_state_all(state["cuda_rng"])
    started = time.monotonic()

    run_config = dict(vars(args))
    run_config["deprecated_async_requested"] = bool(args.async_rollout)
    run_config["async_rollout"] = False
    run_config["pool"] = os.path.abspath(args.pool)
    run_config["pool_sha256"] = file_sha256(args.pool)
    run_config["out_dir"] = os.path.abspath(args.out_dir)
    run_config["network"] = config_dict(model)
    run_config["discount"] = 1.0
    # Record the initialisation honestly. A BC prior is trained on human action
    # labels mined from replays, so a run started from one is NOT replay-free
    # and must not claim to be. The replay-free constraint was a deliberate
    # design choice of the original rl_osfp run, and every such run topped out
    # at 480 on the ladder while the BC-initialised arm reached 972.
    run_config["initialization"] = "bc" if args.init else "random"
    run_config["init_checkpoint"] = os.path.abspath(args.init) if args.init else None
    run_config["replay_action_labels"] = bool(args.init)
    if init_report is not None:
        run_config["init_report"] = init_report
    # Record the encoder the weights were trained against. A checkpoint trained
    # at one MAX_OPT and served at another is a silent policy change, not an
    # error: the sequence length and the g[17] scalar both move. This repo has
    # been bitten by exactly that class of mismatch, so the value is written
    # next to the weights rather than left to be remembered.
    run_config["max_opt"] = NF.MAX_OPT
    run_config["seq"] = NF.SEQ
    ships_to_champion = bool(args.init) and NF.MAX_OPT == 24
    run_config["champion_format_export"] = ships_to_champion
    if args.init and not ships_to_champion:
        print(f"WARNING: MAX_OPT is {NF.MAX_OPT}, not 24, so these checkpoints do NOT "
              "drop into the champion archive. Set PTCG_MAX_OPT=24 to train an "
              "encoder-compatible model.", flush=True)
    with open(os.path.join(args.out_dir, "run_config.json"), "w", encoding="utf-8") as target:
        json.dump({"config": run_config, "pool_source": pool_payload.get("source")},
                  target, indent=2)
    print(
        f"device={device}; rollout_device=cpu; threads={args.threads}; "
        f"network={run_config['network']}; learner_decks={len(learner_decks)}; "
        f"field_decks={len(field_decks)}",
        flush=True,
    )

    if not args.resume and args.init:
        # Keep the behaviour-cloned starting policy as the permanent league
        # anchor. Without this, "historical" self-play starts at period 1 after
        # the first update and the only known-good policy can be forgotten.
        # rebuild_league() preserves the oldest entry when trimming, so period 0
        # survives for the whole run.
        anchor_path = os.path.join(args.out_dir, "league_000.npz")
        export_npz(model, anchor_path)
        league = [LeagueEntry(0, anchor_path)]

    # One pool for the whole run: a spawn start plus an Arena build costs
    # seconds, and the context manager guarantees workers die with the parent.
    # Each period is nevertheless a strict barrier: collect with one frozen
    # behaviour policy, drain every task, then update. PPO is an on-policy
    # algorithm; overlapping these phases was the largest bug in the scaled run.
    with RolloutPool(args.workers, args.threads_per_worker) as rollout_pool:
        for period in range(first_period, args.periods + 1):
            elapsed_minutes = (time.monotonic() - started) / 60.0
            if elapsed_minutes >= args.max_wall_minutes:
                print("wall-time cap reached before next learning period", flush=True)
                break
            if args.anneal_lr:
                progress = (period - 1) / max(1, args.periods - 1)
                learning_rate = args.lr * (1.0 - 0.9 * progress)
                for group in optimizer.param_groups:
                    group["lr"] = learning_rate
            else:
                learning_rate = float(optimizer.param_groups[0]["lr"])
            # Workers load the behaviour policy from disk; a period-unique name
            # keeps their (path, mtime) cache honest across the whole run.
            behaviour_path = os.path.join(work_dir, f"behaviour_{period:03d}.npz")
            export_npz(model, behaviour_path)
            rollout_started = time.monotonic()
            tasks = []
            for game_index in range(args.games_per_period):
                use_self = not league or rng.random() < args.self_play_prob
                if use_self:
                    opponent_path = behaviour_path
                    opponent_label = "current"
                    record_seats = (0, 1)
                else:
                    entry = choose_league_opponent(rng, league)
                    opponent_path = entry.path
                    opponent_label = f"history_{entry.period:03d}"
                    record_seats = (game_index % 2,)
                learner_seat = game_index % 2
                own_deck = weighted_deck(rng, learner_decks)
                opponent_deck = weighted_deck(
                    rng, field_decks, args.uniform_field_prob
                )
                if learner_seat == 0:
                    models = (behaviour_path, opponent_path)
                    decks = (own_deck["cards"], opponent_deck["cards"])
                else:
                    models = (opponent_path, behaviour_path)
                    decks = (opponent_deck["cards"], own_deck["cards"])
                tasks.append(GameTask(
                    left_model=models[0], right_model=models[1],
                    left_deck=decks[0], right_deck=decks[1],
                    record_seats=record_seats, sample=True,
                    temperature=args.temperature,
                    max_recorded=args.max_recorded_per_seat,
                    seed=rng.randrange(2**31),
                    meta={"game": game_index, "learner_seat": learner_seat,
                          "opponent": opponent_label, "learner_deck": own_deck["name"],
                          "opponent_deck": opponent_deck["name"],
                          "policy_period": period},
                ))

            decisions: list[Decision] = []
            game_rows = []
            for outcome in rollout_pool.run(tasks, chunksize=1):
                source_period = outcome.meta.get("policy_period")
                if source_period != period:
                    raise RuntimeError(
                        f"off-policy rollout reached period {period}: task was "
                        f"generated by policy period {source_period}"
                    )
                seats = tuple(outcome.decisions)
                if outcome.error is None:
                    for seat in seats:
                        if outcome.winner in (0, 1):
                            reward = 1.0 if outcome.winner == seat else -1.0
                        else:
                            reward = 0.0
                        for decision in outcome.decisions[seat]:
                            decision.outcome = reward
                            decisions.append(decision)
                game_rows.append({
                    **outcome.meta, "winner": outcome.winner,
                    "steps": outcome.engine_steps,
                    "invalid_actions": outcome.invalid_actions, "error": outcome.error,
                    "step_capped": outcome.step_capped,
                })
            # Tasks are dispatched as a batch, so trim rather than stop early.
            if len(decisions) > args.max_decisions:
                rng.shuffle(decisions)
                decisions = decisions[: args.max_decisions]
            rollout_minutes = (time.monotonic() - rollout_started) / 60.0
            print(
                f"period {period:03d} rollout: {len(game_rows)} games, "
                f"{len(decisions)} decisions, {rollout_minutes:.2f} min, "
                f"invalid={sum(row['invalid_actions'] for row in game_rows)}",
                flush=True,
            )

            if not decisions:
                raise RuntimeError("no valid on-policy decisions were collected")
            update = ppo_update(model, decisions, optimizer, device, rng, args,
                                reference=reference)

            candidate_path = os.path.join(work_dir, f"candidate_{period:03d}.npz")
            export_npz(model, candidate_path)
            evaluations = []
            # Skipping evaluation means we cannot claim the candidate beat the
            # league, so it must not be archived on this period either --
            # `all_pass` stays False rather than defaulting to True.
            run_eval = bool(league) and period % max(1, args.eval_every) == 0
            all_pass = run_eval
            if run_eval:
                outcomes = list(rollout_pool.run(
                    evaluation_tasks(candidate_path, league, learner_decks,
                                     field_decks, args.eval_games),
                    chunksize=1,
                ))
                evaluations = fold_evaluations(outcomes, league)
                all_pass = all(
                    entry.candidate_win_rate > args.archive_threshold for entry in league
                )
            since_archive += 1
            # A max-wait archive is only allowed on an evaluation period.  The
            # previous expression archived unevaluated candidates whenever
            # --eval-every exceeded --archive-max-wait, contradicting the gate.
            archived = not league or (
                run_eval and (all_pass or since_archive >= args.archive_max_wait)
            )
            if archived:
                league_path = os.path.join(args.out_dir, f"league_{period:03d}.npz")
                export_npz(model, league_path)
                league.append(LeagueEntry(period, league_path))
                if len(league) > args.max_history:
                    # Preserve the initial anchor and the most recent opponents.
                    evicted = league.pop(1)
                    try:
                        os.remove(evicted.path)
                    except FileNotFoundError:
                        pass
                since_archive = 0

            matchups: dict[str, dict[str, int]] = {}
            for game in game_rows:
                label = str(game["opponent_deck"])
                row = matchups.setdefault(
                    label,
                    {"games": 0, "wins": 0, "losses": 0, "draws": 0,
                     "errors": 0, "invalid_actions": 0},
                )
                row["games"] += 1
                row["errors"] += int(bool(game["error"]))
                row["invalid_actions"] += int(game["invalid_actions"])
                if game["winner"] == game["learner_seat"]:
                    row["wins"] += 1
                elif game["winner"] == 1 - game["learner_seat"]:
                    row["losses"] += 1
                else:
                    row["draws"] += 1

            period_metrics = {
                "period": period,
                "elapsed_minutes": (time.monotonic() - started) / 60.0,
                "games_count": len(game_rows),
                "decisions": len(decisions),
                "wins": sum(row["winner"] == row["learner_seat"] for row in game_rows),
                "losses": sum(row["winner"] == 1 - row["learner_seat"] for row in game_rows),
                "errors": sum(bool(row["error"]) for row in game_rows),
                "step_caps": sum(bool(row["step_capped"]) for row in game_rows),
                "invalid_actions": sum(row["invalid_actions"] for row in game_rows),
                "policy_lag_counts": {"0": len(game_rows)},
                "learning_rate": learning_rate,
                "update": update,
                "evaluations": evaluations,
                "archived": archived,
                "history_periods": [entry.period for entry in league],
                "gpu": gpu_telemetry(device),
                "matchups": matchups,
                "error_games": [row for row in game_rows if row["error"]][:10],
            }
            if args.record_game_rows:
                period_metrics["games"] = game_rows
            metrics.append(period_metrics)
            export_npz(model, os.path.join(args.out_dir, "model_latest.npz"))
            numbered_checkpoint = (
                period == 1 or period == args.periods or
                period % args.checkpoint_every == 0
            )
            if numbered_checkpoint:
                export_npz(
                    model,
                    os.path.join(args.out_dir, f"model_period_{period:03d}.npz"),
                )
            if ships_to_champion and numbered_checkpoint:
                # Also write the champion archive's own format, so a checkpoint
                # can be gated by swapping model.npz into the proven tarball and
                # changing nothing else. Only correct at MAX_OPT 24, which is
                # why it is gated on the encoder rather than just on --init.
                export_champion_npz(
                    model,
                    os.path.join(args.out_dir, f"champion_period_{period:03d}.npz"))
            torch.save(
                {"period": period, "model": model.state_dict(),
                 "optimizer": optimizer.state_dict(), "config": run_config,
                 "since_archive": since_archive,
                 "python_rng": rng.getstate(),
                 "numpy_rng": np.random.get_state(),
                 "torch_rng": torch.get_rng_state(),
                 "cuda_rng": (torch.cuda.get_rng_state_all()
                              if device.type == "cuda" else None)},
                os.path.join(args.out_dir, "training_state.pt"),
            )
            # Append exactly one completed period. Rewriting a JSON array every
            # update is quadratic I/O and made a multi-million-game run
            # impractical. State is saved first, so a truncated/missing final
            # JSONL row is detectable by audit_run's state-period check.
            with open(os.path.join(args.out_dir, "metrics.jsonl"), "a", encoding="utf-8") as target:
                target.write(json.dumps(period_metrics, separators=(",", ":")) + "\n")
            print(
                f"period {period:02d} update={update} archived={archived} "
                f"history={[entry.period for entry in league]}",
                flush=True,
            )

    if not metrics:
        raise RuntimeError("training ended before completing a learning period")
    export_npz(model, os.path.join(args.out_dir, "model_final.npz"))
    print(f"finished {len(metrics)} periods; exported model_final.npz", flush=True)


if __name__ == "__main__":
    main()
